version: '3.8'

services:
  bot:
    build: .
    container_name: smart-bot
    restart: always
    volumes:
      - ./sessions:/app/sessions
      - ./faiss_index:/app/faiss_index
      - ./knowledge_base.md:/app/knowledge_base.md
      - ./terminals:/app/terminals # Для логов, если нужно
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    command: python3 main.py
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

